[phases.setup]
nixPkgs = [
  "python310", 
  "python310Packages.pip", 
  "mesa", 
  "libGL", 
  "libGLU", 
  "libglvnd", 
  "xorg.libX11", 
  "xorg.libXext", 
  "xorg.libXrender", 
  "xorg.libXi", 
  "xorg.libXrandr", 
  "xorg.libXcursor", 
  "xorg.libXinerama", 
  "xorg.libXxf86vm",
  "xorg.libXtst",
  "xorg.libXScrnSaver",
  "fontconfig",
  "freetype",
  "pkg-config",
  "gcc",
  "glibc",
  "glib",
  "gtk3",
  "cairo",
  "pango",
  "harfbuzz",
  "gdk-pixbuf",
  "atk",
  "ffmpeg"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-cache-dir opencv-python-headless",
  "pip install --no-cache-dir ultralytics",
  "pip install --no-cache-dir Flask gunicorn werkzeug",
  "pip install --no-cache-dir numpy Pillow PyYAML matplotlib seaborn scipy"
]

[variables]
OPENCV_HEADLESS = "1"
LIBGL_ALWAYS_SOFTWARE = "1"
LIBGL_ALWAYS_INDIRECT = "1"
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
OPENCV_VIDEOIO_MSMF_ENABLE_HW_TRANSFORMS = "0"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 1"